import { PrismaClient } from "@prisma/client";
const prisma = new PrismaClient();

async function main() {
  // --- 1. PERMISSIONS ---
  const permissions = [
    {
      slug: "case:read",
      description: "Can view cases",
      isSystemPermission: false,
    },
    {
      slug: "case:write",
      description: "Can edit/approve cases",
      isSystemPermission: false,
    },
    {
      slug: "case:delete",
      description: "Can delete cases",
      isSystemPermission: false,
    },
    {
      slug: "hse:write",
      description: "Can create and modify hse incidents",
      isSystemPermission: false,
    },
    {
      slug: "hse:read",
      description: "Can view hse incidents",
      isSystemPermission: false,
    },
    {
      slug: "hse:delete",
      description: "Can delete hse incidents",
      isSystemPermission: false,
    },
    {
      slug: "participant:write",
      description: "Can create and modify participants",
      isSystemPermission: false,
    },
    {
      slug: "participant:read",
      description: "Can view participants",
      isSystemPermission: false,
    },
    {
      slug: "participant:delete",
      description: "can delete participants",
      isSystemPermission: false,
    },
    {
      slug: "participant:regional_read",
      description: "Can view participants in the same region",
      isSystemPermission: false,
    },
    {
      slug: "admin:view",
      description: "Can view admin dashboard",
      isSystemPermission: true,
    },
    {
      slug: "conference:write",
      description: "Can create conferences",
      isSystemPermission: true,
    },
    {
      slug: "conference:write_regional",
      description: "Can create conferences limited to the user's region",
      isSystemPermission: true,
    },
    {
      slug: "conference:read",
      description: "Can view conferences",
      isSystemPermission: true,
    },
    {
      slug: "conference:read_regional",
      description: "Can view conferences limited by the user's region",
      isSystemPermission: true,
    },
    {
      slug: "conference:delete",
      description: "Can delete conferences",
      isSystemPermission: true,
    },
    {
      slug: "conference:delete_regional",
      description: "Can delete conferences limited to the user's region",
      isSystemPermission: true,
    },
    {
      slug: "users:write",
      description: "Can create new users",
      isSystemPermission: true,
    },
    {
      slug: "users:read",
      description: "Can view users",
      isSystemPermission: true,
    },
    {
      slug: "users:delete",
      description: "Can delete users",
      isSystemPermission: true,
    },
  ];

  // --- 2. ROLES ---
  const roles = [
    {
      name: "SEK_LEDELSE",
      description: "SEK_LEDELSE",
      permissions: [
        "hse:write",
        "hse:read",
        "hse:delete",
        "participant:write",
        "participant:read",
        "participant:delete",
      ],
    },
    {
      name: "KONKOM",
      description: "KONKOM",
      permissions: [
        "case:read",
        "case:write",
        "case:delete",
        "participant:write",
        "participant:read",
        "participant:delete",
      ],
    },
    {
      name: "SEK",
      description: "SEK",
      permissions: [
        "hse:write",
        "hse:read",
        "participant:write",
        "participant:read",
        "participant:delete",
      ],
    },
    {
      name: "TEST",
      description: null,
      permissions: [
        "participant:regional_read",
        "conference:write_regional",
        "conference:read_regional",
        "conference:delete_regional",
      ],
    },
    {
      name: "ADMIN",
      description: "ADMIN",
      permissions: [
        "case:read",
        "case:write",
        "case:delete",
        "hse:write",
        "hse:read",
        "hse:delete",
        "participant:write",
        "participant:read",
        "participant:delete",
        "admin:view",
        "conference:write",
        "conference:read",
        "conference:delete",
        "users:write",
        "users:read",
        "users:delete",
      ],
    },
  ];

  // --- 3. REGIONS ---
  const regions = [
    { name: "Agder", global: false, internal: false, parent: null },
    { name: "Innlandet", global: false, internal: false, parent: null },
    { name: "Møre og Romsdal", global: false, internal: false, parent: null },
    { name: "Nordland", global: false, internal: false, parent: null },
    { name: "Oslo", global: false, internal: false, parent: null },
    { name: "Rogaland", global: false, internal: false, parent: null },
    { name: "Troms", global: false, internal: false, parent: null },
    { name: "Telemark", global: false, internal: false, parent: null },
    { name: "Finnmark", global: false, internal: false, parent: null },
    { name: "Trøndelag", global: false, internal: false, parent: null },
    { name: "Vestfold", global: false, internal: false, parent: null },
    { name: "Vestland", global: false, internal: false, parent: null },
    { name: "Akershus", global: false, internal: false, parent: null },
    { name: "Buskerud", global: false, internal: false, parent: null },
    { name: "Østfold", global: false, internal: false, parent: null },
    { name: "Elevorganisasjonen", global: false, internal: true, parent: null },
    {
      name: "Individuelt Medlemsskap",
      global: false,
      internal: true,
      parent: null,
    },
  ];

  // --- 4. ORGANIZATIONS ---
  const organizations = [
    {
      name: "Eilert Sundt videregående skole, avd Farsund",
      canVote: true,
      region: "Agder",
    },
    { name: "Grim skole", canVote: true, region: "Agder" },
    { name: "Songdalen Ungdomsskole", canVote: true, region: "Agder" },
    { name: "Steinerskolen i Kristiansand", canVote: true, region: "Agder" },
    { name: "Valle Skule", canVote: true, region: "Agder" },
    { name: "Aursmoen skole", canVote: true, region: "Akershus" },
    { name: "Gjettum skole", canVote: true, region: "Akershus" },
    { name: "Haugjordet ungdomsskole", canVote: true, region: "Akershus" },
    { name: "Marikollen ungdomsskole", canVote: true, region: "Akershus" },
    { name: "Nesbru videregående skole", canVote: true, region: "Akershus" },
    { name: "Nordbytun ungdomsskole", canVote: true, region: "Akershus" },
    {
      name: "Roald Amundsen videregående skole",
      canVote: true,
      region: "Akershus",
    },
    { name: "Rælingen videregående skole", canVote: true, region: "Akershus" },
    { name: "Sandvika videregående skole", canVote: true, region: "Akershus" },
    { name: "Ski videregående skole", canVote: true, region: "Akershus" },
    { name: "Steinerskolen på Eidsvoll", canVote: true, region: "Akershus" },
    { name: "Tangenåsen ungdomsskole", canVote: true, region: "Akershus" },
    {
      name: "Akademiet Ypsilon videregående skole AS",
      canVote: true,
      region: "Buskerud",
    },
    { name: "Hokksund ungdomsskole", canVote: true, region: "Buskerud" },
    {
      name: "Båtsfjord Private videregående skole",
      canVote: true,
      region: "Finnmark",
    },
    { name: "Lakselv videregående skole", canVote: true, region: "Finnmark" },
    { name: "Melkarn Oppvekstsenter", canVote: true, region: "Finnmark" },
    { name: "Tana videregående skole", canVote: true, region: "Finnmark" },
    { name: "Elverum Videregående Skole", canVote: true, region: "Innlandet" },
    {
      name: "Engerdal barne- og ungdomsskole",
      canVote: true,
      region: "Innlandet",
    },
    { name: "Jønsberg Videregående Skole", canVote: true, region: "Innlandet" },
    { name: "Kongsvinger Ungdomsskole", canVote: true, region: "Innlandet" },
    {
      name: "Lillehammer Videregående Skole avd Sør",
      canVote: true,
      region: "Innlandet",
    },
    { name: "Otta Ungdomsskole", canVote: true, region: "Innlandet" },
    { name: "Raufoss Videregående Skole", canVote: true, region: "Innlandet" },
    { name: "Solør Videregående Skole", canVote: true, region: "Innlandet" },
    { name: "Gjøvik Videregående Skole", canVote: true, region: "Innlandet" },
    { name: "Sandnes og Bjørnevatn skole", canVote: true, region: "Finnmark" },
    { name: "Vadsø videregående skole", canVote: true, region: "Finnmark" },
    { name: "Vardø videregående skole", canVote: true, region: "Finnmark" },
    { name: "Breilia skole", canVote: true, region: "Finnmark" },
    { name: "Risør Videregående Skole", canVote: true, region: "Agder" },
    { name: "Gausdal Videregående Skole", canVote: true, region: "Innlandet" },
    {
      name: "Eilert Sundt videregående skole, avd Lyngdal",
      canVote: true,
      region: "Agder",
    },
    { name: "Hadeland Videregående Skole", canVote: true, region: "Innlandet" },
    {
      name: "Lena-Valle Videregående Skole",
      canVote: true,
      region: "Innlandet",
    },
    {
      name: "Buskerud videregående skole avd. Rosthaug",
      canVote: true,
      region: "Buskerud",
    },
    {
      name: "Nord-Gudbrandsdalen Videregående Skole avd Otta",
      canVote: true,
      region: "Innlandet",
    },
    { name: "Arendal videregående skole", canVote: true, region: "Agder" },
    { name: "Dahlske videregående skole", canVote: true, region: "Agder" },
    { name: "Lillesand Videregående Skole", canVote: true, region: "Agder" },
    { name: "Eiker videregående skole", canVote: true, region: "Buskerud" },
    { name: "Sam Eyde Videregående Skole", canVote: true, region: "Agder" },
    { name: "Tvedestrand videregående skole", canVote: true, region: "Agder" },
    { name: "Hønefoss videregående skole", canVote: true, region: "Buskerud" },
    {
      name: "Flekkefjord videregående skole avd Flekkefjord",
      canVote: true,
      region: "Agder",
    },
    {
      name: "Kristiansand katedralskole Gimle",
      canVote: true,
      region: "Agder",
    },
    { name: "Kvadraturen videregående skole", canVote: true, region: "Agder" },
    { name: "Mandal Videregående Skole", canVote: true, region: "Agder" },
    { name: "Søgne videregående skole", canVote: true, region: "Agder" },
    { name: "Tangen videregående skole", canVote: true, region: "Agder" },
    { name: "Vennesla videregående skole", canVote: true, region: "Agder" },
    { name: "Vågsbygd videregående skole", canVote: true, region: "Agder" },
    { name: "Torridal ungdomsskole", canVote: true, region: "Agder" },
    { name: "Akademiet Drammen AS", canVote: true, region: "Buskerud" },
    { name: "Lier videregående skole", canVote: true, region: "Buskerud" },
    {
      name: "Briskeby videregående skole AS",
      canVote: true,
      region: "Buskerud",
    },
    { name: "Drammen videregående skole", canVote: true, region: "Buskerud" },
    { name: "Numedal videregående skole", canVote: true, region: "Buskerud" },
    { name: "Gol videregående skole", canVote: true, region: "Buskerud" },
    { name: "Ål videregående skole", canVote: true, region: "Buskerud" },
    { name: "Kongsberg videregående skole", canVote: true, region: "Buskerud" },
    { name: "Åssiden videregående skole", canVote: true, region: "Buskerud" },
    { name: "Ringerike videregående skole", canVote: true, region: "Buskerud" },
    {
      name: "St. Hallvard videregående skole",
      canVote: true,
      region: "Buskerud",
    },
    {
      name: "Akademiet Realfagsgymnas Sandvika",
      canVote: true,
      region: "Akershus",
    },
    {
      name: "Bjørkelangen videregående skole",
      canVote: true,
      region: "Akershus",
    },
    { name: "Fløysbonn skole", canVote: true, region: "Akershus" },
    { name: "Stabekk videregående skole", canVote: true, region: "Akershus" },
    { name: "Alværn ungdomsskole", canVote: true, region: "Akershus" },
    { name: "Vollen ungdomsskole", canVote: true, region: "Akershus" },
    { name: "Bleiker videregående skole", canVote: true, region: "Akershus" },
    { name: "Drømtorp videregående skole", canVote: true, region: "Akershus" },
    { name: "Dyrløkkeåsen skole", canVote: true, region: "Akershus" },
    { name: "Dønski videregående skole", canVote: true, region: "Akershus" },
    { name: "Eidsvoll videregående skole", canVote: true, region: "Akershus" },
    { name: "Hvam videregående skole", canVote: true, region: "Akershus" },
    {
      name: "Lillestrøm videregående skole",
      canVote: true,
      region: "Akershus",
    },
    { name: "Nadderud videregående skole", canVote: true, region: "Akershus" },
    { name: "Nesodden videregående skole", canVote: true, region: "Akershus" },
    { name: "Ramstad skole", canVote: true, region: "Akershus" },
    {
      name: "Rosenvilde videregående skole",
      canVote: true,
      region: "Akershus",
    },
    { name: "Rud videregående skole", canVote: true, region: "Akershus" },
    { name: "Røyken videregående skole", canVote: true, region: "Akershus" },
    { name: "Sandfallet ungdomsskole", canVote: true, region: "Finnmark" },
    { name: "Strømmen videregående skole", canVote: true, region: "Akershus" },
    { name: "Sørumsand videregående skole", canVote: true, region: "Akershus" },
    { name: "Valler videregående skole", canVote: true, region: "Akershus" },
    { name: "Vestby ungdomsskole", canVote: true, region: "Akershus" },
    { name: "Vestby videregående skole", canVote: true, region: "Akershus" },
    {
      name: "Lillehammer Videregående Skole avd Nord",
      canVote: true,
      region: "Innlandet",
    },
    { name: "Bakkeløkka ungdomsskole", canVote: true, region: "Akershus" },
    { name: "Nannestad videregående skole", canVote: true, region: "Akershus" },
    { name: "Harestua skole", canVote: true, region: "Akershus" },
    { name: "Alta videregående skole", canVote: true, region: "Finnmark" },
    {
      name: "Hammerfest videregående skole",
      canVote: true,
      region: "Finnmark",
    },
    { name: "Honningvsåg skole", canVote: true, region: "Finnmark" },
    { name: "Karasjok skole", canVote: true, region: "Finnmark" },
    { name: "Kirkenes videregående skole", canVote: true, region: "Finnmark" },
    { name: "Nordkapp videregående skole", canVote: true, region: "Finnmark" },
    {
      name: "Samisk videregående skole og reindriftsskole avd. Kautokeino",
      canVote: true,
      region: "Finnmark",
    },
    {
      name: "Samisk videregående skole avd. Karasjok",
      canVote: true,
      region: "Finnmark",
    },
    { name: "Hamar Katedralskole", canVote: true, region: "Innlandet" },
    {
      name: "Nord-Østerdal Videregående Skole",
      canVote: true,
      region: "Innlandet",
    },
    {
      name: "Ringsaker Videregående Skole",
      canVote: true,
      region: "Innlandet",
    },
    { name: "Sentrum Videregående Skole", canVote: true, region: "Innlandet" },
    { name: "Stange Videregående Skole", canVote: true, region: "Innlandet" },
    {
      name: "Kolvikbakken ungdomsskole",
      canVote: true,
      region: "Møre og Romsdal",
    },
    { name: "Myklebust Skule", canVote: true, region: "Møre og Romsdal" },
    { name: "Måndalen skule", canVote: true, region: "Møre og Romsdal" },
    {
      name: "Skarbøvik Ungdomsskole",
      canVote: true,
      region: "Møre og Romsdal",
    },
    { name: "Sunndal Ungdomsskole", canVote: true, region: "Møre og Romsdal" },
    {
      name: "Surnadal Videregående Skole",
      canVote: true,
      region: "Møre og Romsdal",
    },
    {
      name: "Åfarnes Barne- Og Ungdomsskole",
      canVote: true,
      region: "Møre og Romsdal",
    },
    {
      name: "Ålesund Videregående Skole avd Volsdalsberga",
      canVote: true,
      region: "Møre og Romsdal",
    },
    { name: "Ballangen skole", canVote: true, region: "Nordland" },
    { name: "Enga Skole", canVote: true, region: "Nordland" },
    { name: "Grane barne- og ungdomsskole", canVote: true, region: "Nordland" },
    {
      name: "Hadsel Videregående Skole avd Melbu",
      canVote: true,
      region: "Nordland",
    },
    { name: "Hemnes Sentralskole", canVote: true, region: "Nordland" },
    { name: "Henningsvær skole", canVote: true, region: "Nordland" },
    { name: "Herøy Skole", canVote: true, region: "Nordland" },
    { name: "Hunstad Ungdomsskole", canVote: true, region: "Nordland" },
    { name: "Husøy Skole", canVote: true, region: "Nordland" },
    { name: "Inndyr Skole", canVote: true, region: "Nordland" },
    { name: "Kabelvåg Ungdomsskole", canVote: true, region: "Nordland" },
    { name: "Kippermoen Ungdomsskole", canVote: true, region: "Nordland" },
    { name: "Korgen Sentralskole", canVote: true, region: "Nordland" },
    { name: "Melbu Skole", canVote: true, region: "Nordland" },
    {
      name: "Narvik Videregående Skole avd Oscarsborg",
      canVote: true,
      region: "Nordland",
    },
    { name: "Rønvik Skole", canVote: true, region: "Nordland" },
    { name: "Saltdal Videregående Skole", canVote: true, region: "Nordland" },
    { name: "Svolvær skole", canVote: true, region: "Nordland" },
    { name: "Tverlandet Skole", canVote: true, region: "Nordland" },
    {
      name: "Utskarpen Barne- og Ungdomsskole",
      canVote: true,
      region: "Nordland",
    },
    { name: "Vega Barne- og Ungdomsskole", canVote: true, region: "Nordland" },
    { name: "Apalløkka skole", canVote: true, region: "Oslo" },
    { name: "Bjørnholt Ungdomsskole", canVote: true, region: "Oslo" },
    { name: "Bjørnholt Videregående Skole", canVote: true, region: "Oslo" },
    { name: "Bøler Skole", canVote: true, region: "Oslo" },
    { name: "Ellingsrud Skole", canVote: true, region: "Oslo" },
    { name: "Hellerud Videregående Skole", canVote: true, region: "Oslo" },
    { name: "Hovseter Skole", canVote: true, region: "Oslo" },
    { name: "Lambertseter grunnskole", canVote: true, region: "Oslo" },
    { name: "Midtstuen Skole", canVote: true, region: "Oslo" },
    { name: "Persbråten Videregående Skole", canVote: true, region: "Oslo" },
    { name: "Ruseløkka Skole", canVote: true, region: "Oslo" },
    { name: "Øvrebyen Videregående Skole", canVote: true, region: "Innlandet" },
    { name: "Alstad ungdomsskole", canVote: true, region: "Nordland" },
    { name: "Andøy Videregående Skole", canVote: true, region: "Nordland" },
    {
      name: "Aust-Lofoten Videregående Skole",
      canVote: true,
      region: "Nordland",
    },
    {
      name: "Bodin videregående skole og maritime fagskole",
      canVote: true,
      region: "Nordland",
    },
    { name: "Bodø Videregående Skole", canVote: true, region: "Nordland" },
    {
      name: "Brønnøysund Videregående Skole",
      canVote: true,
      region: "Nordland",
    },
    {
      name: "Fauske Videregående Skole avd Vestmyra",
      canVote: true,
      region: "Nordland",
    },
    {
      name: "Hadsel Videregående Skole avd Stokmarknes",
      canVote: true,
      region: "Nordland",
    },
    {
      name: "Hilstad Barne- Og Ungdomsskole",
      canVote: true,
      region: "Nordland",
    },
    {
      name: "Kristen Videregående Skole Nordland",
      canVote: true,
      region: "Nordland",
    },
    { name: "Løpsmark Skole", canVote: true, region: "Nordland" },
    {
      name: "Gjermundnes videregående skole",
      canVote: true,
      region: "Møre og Romsdal",
    },
    {
      name: "Narvik Videregående Skole avd Frydenlund",
      canVote: true,
      region: "Nordland",
    },
    {
      name: "Polarsirkelen Videregående Skole",
      canVote: true,
      region: "Nordland",
    },
    {
      name: "Sandnessjøen Videregående Skole",
      canVote: true,
      region: "Nordland",
    },
    {
      name: "Vest-Lofoten Videregående Skole",
      canVote: true,
      region: "Nordland",
    },
    { name: "Ørnes Skole", canVote: true, region: "Nordland" },
    { name: "Meløy videregående skole", canVote: true, region: "Nordland" },
    {
      name: "Sortland videregående skole avd. Sortland, Kleiva og Øksnes",
      canVote: true,
      region: "Nordland",
    },
    { name: "Trysil Videregående Skole", canVote: true, region: "Innlandet" },
    { name: "Lambertseter Videregående Skole", canVote: true, region: "Oslo" },
    { name: "Åsnes Ungdomsskole", canVote: true, region: "Innlandet" },
    { name: "Steinerskolen på Hedemarken", canVote: true, region: "Innlandet" },
    { name: "Valdres Vidaregåande Skule", canVote: true, region: "Innlandet" },
    {
      name: "Ørsta Videregående Skole",
      canVote: true,
      region: "Møre og Romsdal",
    },
    { name: "Etterstad Videregående Skole", canVote: true, region: "Oslo" },
    {
      name: "Storsteigen Videregående Skole",
      canVote: true,
      region: "Innlandet",
    },
    {
      name: "Blindheim ungdomsskole",
      canVote: true,
      region: "Møre og Romsdal",
    },
    {
      name: "Borgund videregående skole",
      canVote: true,
      region: "Møre og Romsdal",
    },
    {
      name: "Hustadvika videregående skole",
      canVote: true,
      region: "Møre og Romsdal",
    },
    { name: "Hersleb Videregående Skole", canVote: true, region: "Oslo" },
    {
      name: "Haram videregående skole",
      canVote: true,
      region: "Møre og Romsdal",
    },
    {
      name: "Kristiansund Videregående Skole",
      canVote: true,
      region: "Møre og Romsdal",
    },
    {
      name: "Molde Videregående Skole",
      canVote: true,
      region: "Møre og Romsdal",
    },
    {
      name: "Romsdal Videregående Skole",
      canVote: true,
      region: "Møre og Romsdal",
    },
    {
      name: "Spjelkavik Videregående Skole",
      canVote: true,
      region: "Møre og Romsdal",
    },
    {
      name: "Stranda Videregående Skole",
      canVote: true,
      region: "Møre og Romsdal",
    },
    {
      name: "Sunndal Videregående Skole",
      canVote: true,
      region: "Møre og Romsdal",
    },
    {
      name: "Sykkylven videregående skole",
      canVote: true,
      region: "Møre og Romsdal",
    },
    {
      name: "Tingvoll Videregående Skole",
      canVote: true,
      region: "Møre og Romsdal",
    },
    {
      name: "Ulstein Videregående Skole",
      canVote: true,
      region: "Møre og Romsdal",
    },
    {
      name: "Volda Videregående Skole",
      canVote: true,
      region: "Møre og Romsdal",
    },
    { name: "Rudolf Steinerskolen i Oslo", canVote: true, region: "Oslo" },
    {
      name: "Atlanten videregående skole",
      canVote: true,
      region: "Møre og Romsdal",
    },
    {
      name: "Rauma videregående skole",
      canVote: true,
      region: "Møre og Romsdal",
    },
    { name: "Blindern Videregående Skole", canVote: true, region: "Oslo" },
    { name: "Edvard Munch Videregående Skole", canVote: true, region: "Oslo" },
    { name: "Elvebakken Videregående Skole", canVote: true, region: "Oslo" },
    { name: "Fagerborg Skole", canVote: true, region: "Oslo" },
    { name: "Foss Videregående Skole", canVote: true, region: "Oslo" },
    {
      name: "Fyrstikkalleén Videregående Skole",
      canVote: true,
      region: "Oslo",
    },
    { name: "Hartvig Nissens Skole", canVote: true, region: "Oslo" },
    { name: "Haugerud Skole", canVote: true, region: "Oslo" },
    { name: "Hauketo Skole", canVote: true, region: "Oslo" },
    { name: "Heltberg Private Gymnas", canVote: true, region: "Oslo" },
    {
      name: "Narvik Videregående Skole avd Solhaugen",
      canVote: true,
      region: "Nordland",
    },
    { name: "Holmlia Skole", canVote: true, region: "Oslo" },
    { name: "Jordal Skole", canVote: true, region: "Oslo" },
    { name: "Kongsskogen Videregående Skole", canVote: true, region: "Oslo" },
    { name: "Kuben Videregående Skole", canVote: true, region: "Oslo" },
    { name: "Lofsrud Skole", canVote: true, region: "Oslo" },
    { name: "Marienlyst Skole", canVote: true, region: "Oslo" },
    { name: "Natur Videregående Skole", canVote: true, region: "Oslo" },
    { name: "Nordberg Skole", canVote: true, region: "Oslo" },
    { name: "Nyskolen i Oslo", canVote: true, region: "Oslo" },
    { name: "Oppsal Skole", canVote: true, region: "Oslo" },
    { name: "Oslo By Steinerskole", canVote: true, region: "Oslo" },
    { name: "Oslo Katedralskole", canVote: true, region: "Oslo" },
    { name: "Ris Skole", canVote: true, region: "Oslo" },
    { name: "Vinstra Videregående Skole", canVote: true, region: "Innlandet" },
    { name: "Fyrstikkalléen Skole", canVote: true, region: "Oslo" },
    { name: "Brannfjell skole", canVote: true, region: "Oslo" },
    { name: "Groruddalen Skole", canVote: true, region: "Oslo" },
    { name: "Frydenberg Skole", canVote: true, region: "Oslo" },
    { name: "Åretta Ungdomsskole", canVote: true, region: "Innlandet" },
    { name: "St. Sunniva Skole", canVote: true, region: "Oslo" },
    { name: "Stasjonsfjellet skole", canVote: true, region: "Oslo" },
    {
      name: "Stiftelsen Den Tyske Skoleforening i Norge",
      canVote: true,
      region: "Oslo",
    },
    { name: "Ullern Videregående Skole", canVote: true, region: "Oslo" },
    { name: "Øraker skole", canVote: true, region: "Oslo" },
    { name: "Bokn Skule", canVote: true, region: "Rogaland" },
    { name: "Haugaland Videregående Skole", canVote: true, region: "Rogaland" },
    { name: "Hetland Videregående Skole", canVote: true, region: "Rogaland" },
    { name: "Jåttå Videregående Skole", canVote: true, region: "Rogaland" },
    { name: "Bø ungdomsskule", canVote: true, region: "Telemark" },
    { name: "Kragerø videregående skole", canVote: true, region: "Telemark" },
    { name: "Mæla ungdomsskole", canVote: true, region: "Telemark" },
    {
      name: "Nome videregående skole, avd Lunde",
      canVote: true,
      region: "Telemark",
    },
    {
      name: "Nome videregående skole, avd Søve",
      canVote: true,
      region: "Telemark",
    },
    {
      name: "Telemark toppidrett ungdomsskole",
      canVote: true,
      region: "Telemark",
    },
    {
      name: "Vest-Telemark videregående skole, avd Dalen og Seljord",
      canVote: true,
      region: "Telemark",
    },
    { name: "Bardu ungdomsskole", canVote: true, region: "Troms" },
    { name: "Gibostad barne- og ungdomsskole", canVote: true, region: "Troms" },
    { name: "Hagebyen skole", canVote: true, region: "Troms" },
    { name: "Kvaløya videregående skole", canVote: true, region: "Troms" },
    { name: "Lavangen skole", canVote: true, region: "Troms" },
    { name: "Longyearbyen skole, grunnskole", canVote: true, region: "Troms" },
    { name: "Nordborg videregående skole", canVote: true, region: "Troms" },
    { name: "Seljestad ungdomsskole", canVote: true, region: "Troms" },
    { name: "Aglo Videregående Skole", canVote: true, region: "Trøndelag" },
    { name: "Byåsen videregående Skole", canVote: true, region: "Trøndelag" },
    { name: "Charlottenlund Ungdomsskole", canVote: true, region: "Trøndelag" },
    { name: "Fosen Videregående Skole", canVote: true, region: "Trøndelag" },
    { name: "Gauldal Videregående Skole", canVote: true, region: "Trøndelag" },
    { name: "Grong Videregående Skole", canVote: true, region: "Trøndelag" },
    { name: "Grong ungdomsskole", canVote: true, region: "Trøndelag" },
    {
      name: "Guri Kunna Videregående Skole",
      canVote: true,
      region: "Trøndelag",
    },
    { name: "Halsen Ungdomsskole", canVote: true, region: "Trøndelag" },
    { name: "Inderøy Videregående Skole", canVote: true, region: "Trøndelag" },
    {
      name: "Johan Bojer videregående skole",
      canVote: true,
      region: "Trøndelag",
    },
    {
      name: "Kyrksæterøra videregående skole",
      canVote: true,
      region: "Trøndelag",
    },
    { name: "Lauvsnes Skole", canVote: true, region: "Trøndelag" },
    { name: "Malm skole", canVote: true, region: "Trøndelag" },
    { name: "Meråker Videregående Skole", canVote: true, region: "Trøndelag" },
    { name: "Mære Landbruksskole", canVote: true, region: "Trøndelag" },
    { name: "Oppdal Videregående Skole", canVote: true, region: "Trøndelag" },
    { name: "Orkdal Videregående Skole", canVote: true, region: "Trøndelag" },
    { name: "Røros Videregående Skole", canVote: true, region: "Trøndelag" },
    { name: "Steinkjer Montessoriskole", canVote: true, region: "Trøndelag" },
    {
      name: "Thora Storm Videregående Skole",
      canVote: true,
      region: "Trøndelag",
    },
    {
      name: "Trondheim international school",
      canVote: true,
      region: "Trøndelag",
    },
    { name: "Vikhammer Ungdomsskole", canVote: true, region: "Trøndelag" },
    { name: "Levanger Videregående Skole", canVote: true, region: "Trøndelag" },
    {
      name: "Nord-Troms videregående skole (avd. Nordreisa og Skjervøy)",
      canVote: true,
      region: "Troms",
    },
    { name: "Sørreisa sentralskole", canVote: true, region: "Troms" },
    {
      name: "Bybroen Videregående Skole AS",
      canVote: true,
      region: "Trøndelag",
    },
    {
      name: "Senja videregående skole, avd. Finnfjordbotn",
      canVote: true,
      region: "Troms",
    },
    { name: "Sjøvegan videregående skole", canVote: true, region: "Troms" },
    { name: "Nordkjosbotn videregående skole", canVote: true, region: "Troms" },
    { name: "Sommerlyst skole", canVote: true, region: "Troms" },
    { name: "Trondheim Katedralskole", canVote: true, region: "Trøndelag" },
    {
      name: "Steinerskolen i Trondheim, Grunnskole",
      canVote: true,
      region: "Trøndelag",
    },
    {
      name: "Steinkjer Videregående Skole",
      canVote: true,
      region: "Trøndelag",
    },
    { name: "Strand Videregående Skole", canVote: true, region: "Rogaland" },
    { name: "Tiller Videregående Skole", canVote: true, region: "Trøndelag" },
    { name: "Øygard Ungdomsskole", canVote: true, region: "Rogaland" },
    { name: "Verdal Videregående Skole", canVote: true, region: "Trøndelag" },
    {
      name: "Ytre Namdal Videregående Skole",
      canVote: true,
      region: "Trøndelag",
    },
    { name: "Steinerskolen Rotvoll", canVote: true, region: "Trøndelag" },
    { name: "Bergeland Videregående Skole", canVote: true, region: "Rogaland" },
    { name: "Bryne Videregående Skole", canVote: true, region: "Rogaland" },
    { name: "Dalane Videregående Skole", canVote: true, region: "Rogaland" },
    { name: "Godalen Videregående Skole", canVote: true, region: "Rogaland" },
    {
      name: "Vardafjell videregående skole",
      canVote: true,
      region: "Rogaland",
    },
    { name: "Randaberg Videregående Skole", canVote: true, region: "Rogaland" },
    { name: "Sauda Videregående Skole", canVote: true, region: "Rogaland" },
    { name: "Akademiet Sandnes", canVote: true, region: "Rogaland" },
    { name: "Vågen Videregående Skole", canVote: true, region: "Rogaland" },
    { name: "Øksnevad Videregående Skole", canVote: true, region: "Rogaland" },
    { name: "Ølen Videregående Skole", canVote: true, region: "Rogaland" },
    { name: "Hjelmeland Ungdomsskule", canVote: true, region: "Rogaland" },
    { name: "St. Olav Videregående Skole", canVote: true, region: "Rogaland" },
    { name: "Skullerud Skole", canVote: true, region: "Oslo" },
    { name: "Sofienberg Skole", canVote: true, region: "Oslo" },
    { name: "Stovner Videregående Skole", canVote: true, region: "Oslo" },
    { name: "Forsand Skule", canVote: true, region: "Rogaland" },
    { name: "Skeisvang Videregående Skole", canVote: true, region: "Rogaland" },
    { name: "Sagene Skole", canVote: true, region: "Oslo" },
    { name: "Ulsrud Videregående Skole", canVote: true, region: "Oslo" },
    { name: "Sollerudstranda Skole", canVote: true, region: "Oslo" },
    { name: "Skøyenåsen Skole", canVote: true, region: "Oslo" },
    {
      name: "Hjalmar Johansen videregående skole",
      canVote: true,
      region: "Telemark",
    },
    { name: "Salangen skole", canVote: true, region: "Troms" },
    { name: "Bamble videregående skole", canVote: true, region: "Telemark" },
    { name: "Bø videregåande skule", canVote: true, region: "Telemark" },
    { name: "Meldal Videregående Skole", canVote: true, region: "Trøndelag" },
    { name: "Notodden videregående skole", canVote: true, region: "Telemark" },
    { name: "Rjukan videregående skole", canVote: true, region: "Telemark" },
    { name: "Skien videregående skole", canVote: true, region: "Telemark" },
    { name: "Bardufoss videregående skole", canVote: true, region: "Troms" },
    { name: "Breivang videregående skole", canVote: true, region: "Troms" },
    { name: "Finnsnes ungdomsskole", canVote: true, region: "Troms" },
    { name: "Heggen videregående skole", canVote: true, region: "Troms" },
    { name: "Ishavsbyen videregående skole", canVote: true, region: "Troms" },
    { name: "Kongsbakken videregående skole", canVote: true, region: "Troms" },
    {
      name: "Longyearbyen skole, videregående skole",
      canVote: true,
      region: "Troms",
    },
    { name: "Lærlingrådet i Trøndelag", canVote: true, region: "Trøndelag" },
    {
      name: "Senja videregående skole, avd. Gibostad",
      canVote: true,
      region: "Troms",
    },
    { name: "Malvik Videregående Skole", canVote: true, region: "Trøndelag" },
    { name: "Tromsdalen videregående skole", canVote: true, region: "Troms" },
    { name: "Strinda Videregående Skole", canVote: true, region: "Trøndelag" },
    { name: "Tromstun skole", canVote: true, region: "Troms" },
    { name: "Melhus Videregående Skole", canVote: true, region: "Trøndelag" },
    {
      name: "Olav Duun Videregående Skole",
      canVote: true,
      region: "Trøndelag",
    },
    { name: "Ole Vig Videregående Skole", canVote: true, region: "Trøndelag" },
    {
      name: "Skjetlein Videregående Skole",
      canVote: true,
      region: "Trøndelag",
    },
    { name: "Kopervik Videregående Skole", canVote: true, region: "Rogaland" },
    { name: "Malangen Skole", canVote: true, region: "Troms" },
    { name: "Stavanger Katedralskole", canVote: true, region: "Rogaland" },
    { name: "Åfjord videregående Skole", canVote: true, region: "Trøndelag" },
    { name: "Årlivoll skole", canVote: true, region: "Trøndelag" },
    { name: "Øya Videregående Skole", canVote: true, region: "Trøndelag" },
    { name: "Revetal ungdomsskole", canVote: true, region: "Vestfold" },
    { name: "Sande Videregående skole", canVote: true, region: "Vestfold" },
    {
      name: "Steinerskolen i Vestfold - Grunnskolen på Nøtterøy",
      canVote: true,
      region: "Vestfold",
    },
    {
      name: "Steinerskolen i Vestfold - Slottsfjellet videregående",
      canVote: true,
      region: "Vestfold",
    },
    { name: "Askvoll Skole", canVote: true, region: "Vestland" },
    {
      name: "Bergen Katedralskole avd Kyrre",
      canVote: true,
      region: "Vestland",
    },
    { name: "Dale Videregående Skole", canVote: true, region: "Vestland" },
    { name: "Eid Videregående Skole", canVote: true, region: "Vestland" },
    { name: "Førde Ungdomsskole", canVote: true, region: "Vestland" },
    { name: "Granvin ungdomsskole", canVote: true, region: "Vestland" },
    { name: "Halbrend Skole", canVote: true, region: "Vestland" },
    { name: "Hauso Skole", canVote: true, region: "Vestland" },
    { name: "Kjøkkelvik skole", canVote: true, region: "Vestland" },
    { name: "Krokeide videregående skole", canVote: true, region: "Vestland" },
    { name: "Kvam Ungdomsskole", canVote: true, region: "Vestland" },
    { name: "Kvam vidaregåande skule", canVote: true, region: "Vestland" },
    {
      name: "Langhaugen Videregående Skole",
      canVote: true,
      region: "Vestland",
    },
    { name: "UWC Red Cross Nordic", canVote: true, region: "Vestland" },
    { name: "Voss Videregående Skole", canVote: true, region: "Vestland" },
    { name: "Årdal Videregående Skole", canVote: true, region: "Vestland" },
    { name: "Borge ungdomsskole", canVote: true, region: "Østfold" },
    { name: "Halden videregående skole", canVote: true, region: "Østfold" },
    { name: "Haugeåsen ungdomsskole", canVote: true, region: "Østfold" },
    {
      name: "Kirkebygden ungdomsskole (Våler)",
      canVote: true,
      region: "Østfold",
    },
    {
      name: "Knapstad brane- og ungdomsskole",
      canVote: true,
      region: "Østfold",
    },
    { name: "Kråkerøy ungdomsskole", canVote: true, region: "Østfold" },
    { name: "Mysen videregående skole", canVote: true, region: "Østfold" },
    { name: "Spydeberg ungdomsskole", canVote: true, region: "Østfold" },
    {
      name: "Steinerskolen i Moss, grunnskole",
      canVote: true,
      region: "Østfold",
    },
    {
      name: "Steinerskolen i Moss, videregående skole",
      canVote: true,
      region: "Østfold",
    },
    { name: "Trøgstad ungdomsskole", canVote: true, region: "Østfold" },
    { name: "Vestbygda ungdomsskole", canVote: true, region: "Østfold" },
    {
      name: "Distriktskomiteene i Operasjon Dagsverk",
      canVote: false,
      region: "Elevorganisasjonen",
    },
    {
      name: "Elevorganisasjonen i Telemark",
      canVote: false,
      region: "Elevorganisasjonen",
    },
    {
      name: "Elevorganisasjonen i Vestfold",
      canVote: false,
      region: "Elevorganisasjonen",
    },
    {
      name: "Gjest med innvilget talerett",
      canVote: false,
      region: "Elevorganisasjonen",
    },
    {
      name: "Olsvikåsen Videregående Skole",
      canVote: true,
      region: "Vestland",
    },
    {
      name: "Amalie Skram Videregående Skole",
      canVote: true,
      region: "Vestland",
    },
    { name: "Arna Videregående Skole", canVote: true, region: "Vestland" },
    { name: "Austrheim Videregående Skole", canVote: true, region: "Vestland" },
    { name: "Austevoll Videregående Skole", canVote: true, region: "Vestland" },
    { name: "Os Gymnas", canVote: true, region: "Vestland" },
    { name: "Bergen Katedralskole", canVote: true, region: "Vestland" },
    { name: "Fusa Videregående Skole", canVote: true, region: "Vestland" },
    { name: "Høyanger Videregående Skole", canVote: true, region: "Vestland" },
    {
      name: "Fyllingsdalen Videregående Skole",
      canVote: true,
      region: "Vestland",
    },
    { name: "Knarvik Videregående Skole", canVote: true, region: "Vestland" },
    { name: "Metis Videregående Skole AS", canVote: true, region: "Vestland" },
    {
      name: "Nordahl Grieg Videregående Skole",
      canVote: true,
      region: "Vestland",
    },
    { name: "Odda Videregående Skole", canVote: true, region: "Vestland" },
    { name: "Sogndal Videregående Skole", canVote: true, region: "Vestland" },
    { name: "Os Videregående Skole", canVote: true, region: "Vestland" },
    {
      name: "Bømlo Videregående skole, avd. Rubbestadneset",
      canVote: true,
      region: "Vestland",
    },
    { name: "Osterøy Videregående Skole", canVote: true, region: "Vestland" },
    { name: "Slåtthaug Videregående Skole", canVote: true, region: "Vestland" },
    {
      name: "Sotra Videregående Skole avd Bildøy",
      canVote: true,
      region: "Vestland",
    },
    {
      name: "Sotra Videregående Skole avd Sund",
      canVote: true,
      region: "Vestland",
    },
    { name: "Stend Videregående Skole", canVote: true, region: "Vestland" },
    { name: "Stord Videregående Skole", canVote: true, region: "Vestland" },
    { name: "Tertnes Videregående Skole", canVote: true, region: "Vestland" },
    { name: "Voss Gymnas", canVote: true, region: "Vestland" },
    { name: "Årstad Videregående Skole", canVote: true, region: "Vestland" },
    { name: "Åsane Videregående Skole", canVote: true, region: "Vestland" },
    { name: "Firda Videregående Skole", canVote: true, region: "Vestland" },
    { name: "Flora Videregående Skole", canVote: true, region: "Vestland" },
    { name: "Måløy Videregående Skole", canVote: true, region: "Vestland" },
    { name: "Generalsekretær", canVote: false, region: "Elevorganisasjonen" },
    { name: "Stryn Videregående Skole", canVote: true, region: "Vestland" },
    {
      name: "Elevorganisasjonen i Oslo Øst",
      canVote: false,
      region: "Elevorganisasjonen",
    },
    { name: "Strandebarm Skule", canVote: true, region: "Vestland" },
    { name: "Sund Ungdomsskole", canVote: true, region: "Vestland" },
    { name: "Kyrkjekrinsen ungdomsskole", canVote: true, region: "Vestland" },
    { name: "Sandsli videregående skole", canVote: true, region: "Vestland" },
    { name: "Førde videregående skule", canVote: true, region: "Vestland" },
    {
      name: "Elevorganisasjonen i Nordland",
      canVote: false,
      region: "Elevorganisasjonen",
    },
    {
      name: "Elevorganisasjonen i Oslo Vest",
      canVote: false,
      region: "Elevorganisasjonen",
    },
    {
      name: "Elevorganisasjonen i Trøndelag",
      canVote: false,
      region: "Elevorganisasjonen",
    },
    {
      name: "Elevorganisasjonen i Innlandet",
      canVote: false,
      region: "Elevorganisasjonen",
    },
    {
      name: "Elevorganisasjonen i Vestland",
      canVote: false,
      region: "Elevorganisasjonen",
    },
    {
      name: "Elevorganisasjonen i Rogaland",
      canVote: false,
      region: "Elevorganisasjonen",
    },
    {
      name: "Elevorganisasjonen i Agder",
      canVote: false,
      region: "Elevorganisasjonen",
    },
    {
      name: "Elevorganisasjonen i Oslo",
      canVote: false,
      region: "Elevorganisasjonen",
    },
    {
      name: "Elevorganisasjonen i Møre og Romsdal",
      canVote: false,
      region: "Elevorganisasjonen",
    },
    {
      name: "Elevorganisasjonen i Oslo Sentrum",
      canVote: false,
      region: "Elevorganisasjonen",
    },
    {
      name: "Elevorganisasjonen i Trondheim",
      canVote: false,
      region: "Elevorganisasjonen",
    },
    {
      name: "Elevorganisasjonen i Bergen",
      canVote: false,
      region: "Elevorganisasjonen",
    },
    { name: "Akademiet Fredrikstad AS", canVote: true, region: "Østfold" },
    {
      name: "Elevorganisasjonen i Buskerud",
      canVote: false,
      region: "Elevorganisasjonen",
    },
    { name: "Askim ungdomsskole", canVote: true, region: "Østfold" },
    {
      name: "Elevorganisasjonen i Akershus",
      canVote: false,
      region: "Elevorganisasjonen",
    },
    {
      name: "Elevorganisasjonen i Østfold",
      canVote: false,
      region: "Elevorganisasjonen",
    },
    {
      name: "Elevorganisasjonen i Troms",
      canVote: false,
      region: "Elevorganisasjonen",
    },
    {
      name: "Elevorganisasjonen i Finnmark",
      canVote: false,
      region: "Elevorganisasjonen",
    },
    { name: "Færder videregående skole", canVote: true, region: "Vestfold" },
    { name: "Malakoff videregående skole", canVote: true, region: "Østfold" },
    { name: "Nøtterøy videregående skole", canVote: true, region: "Vestfold" },
    { name: "Tjodalyng skole", canVote: true, region: "Vestfold" },
    { name: "Steinerskolen i Fredrikstad", canVote: true, region: "Østfold" },
    { name: "Askim videregående skole", canVote: true, region: "Østfold" },
    { name: "Borg videregående skole", canVote: true, region: "Østfold" },
    {
      name: "Frederik II videregående skole",
      canVote: true,
      region: "Østfold",
    },
    { name: "Glemmen videregående skole", canVote: true, region: "Østfold" },
    { name: "Greåker videregående skole", canVote: true, region: "Østfold" },
    { name: "Kalnes videregående skole", canVote: true, region: "Østfold" },
    {
      name: "Kirkeparken videregående skole",
      canVote: true,
      region: "Østfold",
    },
    { name: "Mysen ungdomsskole", canVote: true, region: "Østfold" },
    { name: "Askøy Videregående Skole", canVote: true, region: "Vestland" },
    { name: "Hvaler barne- og ungdomsskole", canVote: true, region: "Østfold" },
    {
      name: "Bømlo Videregående Skole, avd. Leite",
      canVote: true,
      region: "Vestland",
    },
    { name: "Kvernhuset ungdomsskole", canVote: true, region: "Østfold" },
    { name: "Sentralstyret", canVote: false, region: "Elevorganisasjonen" },
    { name: "Valgkomitéen", canVote: false, region: "Elevorganisasjonen" },
    { name: "Kontrollkomiteen", canVote: false, region: "Elevorganisasjonen" },
    {
      name: "Hovedkomiteen i Operasjon Dagsverk",
      canVote: false,
      region: "Elevorganisasjonen",
    },
    { name: "Ordstyrerbordet", canVote: false, region: "Elevorganisasjonen" },
    { name: "Referenter", canVote: false, region: "Elevorganisasjonen" },
    {
      name: "Holmestrand videregående skole",
      canVote: true,
      region: "Vestfold",
    },
    {
      name: "Stiftelsen Toppidrettsgymnaset i Telemark",
      canVote: true,
      region: "Telemark",
    },
    { name: "Asker videregående skole", canVote: true, region: "Akershus" },
    {
      name: "Rudolf Steinerskolen stiftelsen avd. Undervisning (Nesodden)",
      canVote: true,
      region: "Akershus",
    },
    {
      name: "Hillesøyskolen - Brensholmen skole",
      canVote: true,
      region: "Troms",
    },
    {
      name: "Individuelt medlem i Elevorganisasjonen",
      canVote: false,
      region: "Individuelt Medlemsskap",
    },
    {
      name: "Nord-Salten videregående skole (avd Joarkkaskåvllå og Steigen)",
      canVote: true,
      region: "Nordland",
    },
    {
      name: "Flekkefjord Vgs studiested Kvinesdal",
      canVote: true,
      region: "Agder",
    },
    { name: "Hareid ungdomsskole", canVote: true, region: "Møre og Romsdal" },
    { name: "Manndalen ungdomsskole", canVote: true, region: "Troms" },
    { name: "Skoleskipet Gann", canVote: true, region: "Rogaland" },
    { name: "Mosjøen Videregående Skole", canVote: true, region: "Nordland" },
    { name: "Heimdal Videregående Skole", canVote: true, region: "Trøndelag" },
    {
      name: "Charlottenlund Videregående Skole",
      canVote: true,
      region: "Trøndelag",
    },
    {
      name: "Laksevåg og Bergen Maritime Videregående Skole",
      canVote: true,
      region: "Vestland",
    },
    {
      name: "Ålesund videregående skole avd Fagerlia",
      canVote: true,
      region: "Møre og Romsdal",
    },
    {
      name: "Setesdal Videregående Skole avd Valle, Hovden og Hornes",
      canVote: true,
      region: "Agder",
    },
    { name: "Sandnes Videregående Skole", canVote: true, region: "Rogaland" },
    { name: "Nydalen Videregående Skole", canVote: true, region: "Oslo" },
    { name: "Vika videregående skole", canVote: true, region: "Oslo" },
  ];

  // --- 5. WHITELIST USERS ---
  const users = [
    {
      email: "birk@elev.no",
      name: null,
      role: "ADMIN",
      region: "Elevorganisasjonen",
    },
    {
      email: "birk.monsen@gmail.com",
      name: null,
      role: "TEST",
      region: "Oslo",
    },
    { email: "bmo006.email@gmail.com", name: null, role: null, region: null },
  ];

  // --- SEED LOGIC ---

  // 1. Permissions
  console.log("Seeding Permissions...");
  for (const p of permissions) {
    await prisma.permission.upsert({
      where: { slug: p.slug },
      update: { isSystemPermission: p.isSystemPermission },
      create: p,
    });
  }

  // 2. Roles
  console.log("Seeding Roles...");
  for (const r of roles) {
    await prisma.role.upsert({
      where: { name: r.name },
      update: {
        permissions: {
          set: [], // Clear old
          connect: r.permissions.map((slug) => ({ slug })),
        },
      },
      create: {
        name: r.name,
        description: r.description,
        permissions: {
          connect: r.permissions.map((slug) => ({ slug })),
        },
      },
    });
  }

  // 3. Regions
  console.log("Seeding Regions...");
  for (const r of regions) {
    await prisma.region.upsert({
      where: { name: r.name },
      update: {},
      create: {
        name: r.name,
        global: r.global,
        internal: r.internal,
      },
    });
  }
  // Link parents in second pass
  for (const r of regions) {
    if (r.parent) {
      await prisma.region.update({
        where: { name: r.name },
        data: {
          parent: { connect: { name: r.parent } },
        },
      });
    }
  }

  // 4. Organizations
  console.log("Seeding Organizations...");
  for (const o of organizations) {
    if (!o.region) {
      console.warn(`Skipping org ${o.name} because it has no region.`);
      continue;
    }
    await prisma.organization.upsert({
      where: { name: o.name },
      update: { canVote: o.canVote },
      create: {
        name: o.name,
        canVote: o.canVote,
        region: { connect: { name: o.region } },
      },
    });
  }

  // 5. Users
  console.log("Seeding Users...");
  for (const u of users) {
    await prisma.whitelist.upsert({
      where: { email: u.email },
      update: { name: u.name },
      create: {
        email: u.email,
        name: u.name,
        role: u.role ? { connect: { name: u.role } } : undefined,
        region: u.region ? { connect: { name: u.region } } : undefined,
      },
    });
  }
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
